-- MySQL Script generated by MySQL Workbench
-- Mon May 29 12:08:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `numero_cliente` INT NOT NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`numero_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direcciones_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direcciones_envio` (
  `id_direccion_envio` INT NULL,
  `clientes_numero_cliente` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_direccion_envio`),
  CONSTRAINT `fk_direcciones_envio_clientes`
    FOREIGN KEY (`clientes_numero_cliente`)
    REFERENCES `mydb`.`clientes` (`numero_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_direcciones_envio_clientes_idx` ON `mydb`.`direcciones_envio` (`clientes_numero_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `numero_pedido` INT NOT NULL,
  `clientes_numero_cliente` INT NOT NULL,
  `fecha_pedido` DATE NULL,
  PRIMARY KEY (`numero_pedido`),
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_numero_cliente`)
    REFERENCES `mydb`.`clientes` (`numero_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedidos_clientes1_idx` ON `mydb`.`pedidos` (`clientes_numero_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulos` (
  `numero_articulo` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`numero_articulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos_has_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos_has_articulos` (
  `pedidos_numero_pedido` INT NOT NULL,
  `articulos_numero_articulo` INT NOT NULL,
  `cantidad_articulo` INT NULL,
  PRIMARY KEY (`pedidos_numero_pedido`, `articulos_numero_articulo`),
  CONSTRAINT `fk_pedidos_has_articulos_pedidos1`
    FOREIGN KEY (`pedidos_numero_pedido`)
    REFERENCES `mydb`.`pedidos` (`numero_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_articulos_articulos1`
    FOREIGN KEY (`articulos_numero_articulo`)
    REFERENCES `mydb`.`articulos` (`numero_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedidos_has_articulos_articulos1_idx` ON `mydb`.`pedidos_has_articulos` (`articulos_numero_articulo` ASC) VISIBLE;

CREATE INDEX `fk_pedidos_has_articulos_pedidos1_idx` ON `mydb`.`pedidos_has_articulos` (`pedidos_numero_pedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`fabricas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabricas` (
  `numero_fabrica` INT NOT NULL,
  `articulos_numero_articulo` INT NOT NULL,
  `telefono_contacto` INT NULL,
  `existencias` INT NULL,
  `cantidad_articulos_provee` INT NULL,
  `fabricas_alternativas` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero_fabrica`),
  CONSTRAINT `fk_fabricas_articulos1`
    FOREIGN KEY (`articulos_numero_articulo`)
    REFERENCES `mydb`.`articulos` (`numero_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_fabricas_articulos1_idx` ON `mydb`.`fabricas` (`articulos_numero_articulo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
